---
- name: Create nvim config folder
  ansible.builtin.file:
    path: /home/ubuntu/.config/nvim/
    state: directory

- name: Set neovim config
  ansible.builtin.copy:
    src: /home/ubuntu/developer-tools/config/init.vim
    dest: /home/ubuntu/.config/nvim/init.vim
    owner: ubuntu
    group: ubuntu
    mode: '0744'

- name: Create vim plug folder
  ansible.builtin.file:
    path: /home/ubuntu/.local/share/nvim/site/autoload/
    state: directory

- name: Downwload neovim config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/ubuntu/.local/share/nvim/site/autoload/plug.vim
    mode: '0740'

#   - name: Set neovim config
#     become: true
#     ansible.builtin.get_url:
#       url: https://raw.githubusercontent.com/sephioh/developer-tools/master/config/init.vim
#       dest: /home/ubuntu/.config/nvim/
#       mode: '0740'
#       owner: ubuntu
#       group: ubuntu
