---
- name: user name
  community.general.git_config:
      name: user.name
      scope: global
      value: 'Abraão Alcântara'

- name: user email
  community.general.git_config:
      name: user.email
      scope: global
      value: sephioh@gmail.com

- name: excludes file
  community.general.git_config:
      name: core.excludesFile
      scope: global
      value: ~/.gitignore

- name: default branch
  community.general.git_config:
      name: init.defaultBranch
      scope: global
      value: ~/.gitignore
