---
- name: user name
  community.general.git_config:
      name: user.name
      scope: global
      value: 'Abraão Alcântara'

- name: user email
  community.general.git_config:
      name: user.email
      scope: global
      value: sephioh@gmail.com

- name: excludes file
  community.general.git_config:
      name: core.excludesFile
      scope: global
      value: ~/.gitignore

- name: copy default .gitignore
  ansible.builtin.copy:
    src: /home/ubuntu/developer-tools/config/.gitignore_global
    dest: /home/ubuntu/.gitignore
    owner: ubuntu
    group: ubuntu
    mode: '0744'

- name: default branch
  community.general.git_config:
      name: init.defaultBranch
      scope: global
      value: master
